openapi: 3.0.3
info:
  title: AU Online CS Reviews API - OpenAPI 3.0
  description: |-
    This defines the API endpoints that allow the reviews application to run.
  version: 1.0.11
tags:
  - name: course
    description: Everything about the program's courses
  - name: professor
    description: Access to professor data
  - name: user
    description: Operations about user
paths:
  /courses:
    get:
      tags:
        - course
      summary: Get all courses
      description: Get all courses with a list of professors that teach that course and some average course metrics
      operationId: getCourses
      responses:
        "200":
          description: Courses retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Courses"
        "401":
          description: unauthorized
        "403":
          description: forbidden
        "500":
          description: internal server error
      security:
        - auonline_auth:
            - read:courses
components:
  schemas:
    Courses:
      type: object
      properties:
        courses:
          type: array
          items:
            $ref: "#/components/schemas/Course"
    Course:
      type: object
      properties:
        courseId:
          type: integer
        courseCode:
          type: string
        name:
          type: string
        professors:
          type: array
          items:
            $ref: "#/components/schemas/MiniProfessor"
        averageMetrics:
          $ref: "#/components/schemas/CourseAverageMetrics"
    CourseAverageMetrics:
      type: object
      properties:
        difficulty:
          type: integer
          #TODO: ensure we want a min/max and that this is correct syntax
          minimum: 0
          maximum: 5
        value:
          type: integer
          minimum: 0
          maximum: 5
        hoursPerWeek:
          type: integer
        grade:
          type: string #TODO: create custom type for grade enum?
    MiniProfessor:
      type: object
      properties:
        professorId:
          type: integer
        name:
          type: string
        overallAverage:
          type: integer
  securitySchemes:
    auonline_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize # TODO : replace with auth0 provided url
          scopes:
            "read:courses": "allows a user to read course data"
